import type { ThemeStore } from "./interface";

export const DefaultThemes: ThemeStore = {
  arcDark: {
    author: "ArcOS Team",
    version: "1.0.0",
    name: "ArcOS Dark",
    anim: true,
    noGlass: false,
    sharp: false,
    theme: "dark",
    wallpaper: "img04",
    taskbarCentered: false,
    taskbarLabels: false,
    taskbarPosition: "",
    docked: false,
    accent: "70D6FF",
    smallStart: true,
    titleButtons: "default",
    titlebarLarge: false,
    titlebarLeft: false,
    taskbarColored: false,
  },
  arcLight: {
    author: "ArcOS Team",
    version: "1.0.0",
    name: "ArcOS Light",
    anim: true,
    noGlass: false,
    sharp: false,
    theme: "light",
    wallpaper: "img05",
    taskbarCentered: false,
    taskbarLabels: false,
    taskbarPosition: "",
    docked: false,
    accent: "70D6FF",
    smallStart: true,
    titleButtons: "default",
    titlebarLarge: false,
    titlebarLeft: false,
    taskbarColored: false,
  },
  theHague: {
    author: "Aron Wagener",
    version: "1.0.0",
    name: "The Hague",
    anim: true,
    noGlass: false,
    sharp: false,
    theme: "dark",
    wallpaper: "img13",
    taskbarCentered: false,
    taskbarLabels: true,
    taskbarPosition: "",
    docked: true,
    accent: "0A0",
    smallStart: false,
    titleButtons: "default",
    titlebarLarge: true,
    titlebarLeft: false,
    taskbarColored: false,
  },
  wacky: {
    author: "Izaak Kuipers",
    version: "1.0.0",
    name: "Wacky",
    anim: true,
    noGlass: false,
    sharp: false,
    theme: "dark",
    wallpaper: "img03",
    taskbarCentered: true,
    taskbarLabels: true,
    taskbarPosition: "vertical",
    docked: false,
    accent: "fa0",
    smallStart: true,
    titleButtons: "og",
    titlebarLarge: true,
    titlebarLeft: true,
    taskbarColored: false,
  },
  performance: {
    author: "ArcOS Team",
    version: "1.0.0",
    name: "Optimal Performance",
    anim: false,
    noGlass: true,
    sharp: true,
    theme: "dark",
    wallpaper: "img0",
    taskbarCentered: false,
    taskbarLabels: false,
    taskbarPosition: "",
    docked: true,
    accent: "FFF",
    smallStart: true,
    titleButtons: "default",
    titlebarLarge: false,
    titlebarLeft: false,
    taskbarColored: false,
  },
  wandelbos: {
    version: "1.0.0",
    name: "Wandelbos",
    author: "Izaak",
    anim: true,
    noGlass: false,
    sharp: false,
    theme: "dark",
    wallpaper: "img08",
    accent: "91F5AD",
    docked: true,
    taskbarCentered: false,
    taskbarLabels: false,
    taskbarPosition: "",
    smallStart: true,
    titleButtons: "default",
    titlebarLarge: false,
    titlebarLeft: false,
    taskbarColored: true,
  },
  scheveningen: {
    version: "1.0.0",
    name: "Scheveningen",
    author: "Izaak & keesvv",
    anim: true,
    noGlass: false,
    sharp: false,
    theme: "dark",
    wallpaper: "img14",
    accent: "264653",
    docked: true,
    taskbarCentered: false,
    taskbarLabels: false,
    taskbarPosition: "",
    smallStart: true,
    titleButtons: "default",
    titlebarLarge: false,
    titlebarLeft: false,
    taskbarColored: true,
  },
};
