export { default as ArcAppMimeIcon } from "../../assets/mimetypes/application-arcapp.svg";
export { default as DefaultMimeIcon } from "../../assets/mimetypes/application-default.svg";
export { default as JsonMimeIcon } from "../../assets/mimetypes/application-json.svg";
export { default as PdfMimeIcon } from "../../assets/mimetypes/application-pdf.svg";
export { default as SvgMimeIcon } from "../../assets/mimetypes/application-svg.svg";
export { default as CompressMimeIcon } from "../../assets/mimetypes/application-x-compress.svg";
export { default as AudioMimeIcon } from "../../assets/mimetypes/audio-x-generic.svg";
export { default as ImageMimeIcon } from "../../assets/mimetypes/image-x-generic.svg";
export { default as PlainMimeIcon } from "../../assets/mimetypes/text-plain.svg";
