import { get } from "svelte/store";
import type { App } from "../applogic/interface";
import { ArcOSVersion } from "../env/main";
import { ErrorButton, ErrorMessage, ErrorMessages } from "./app";

export function errorMessage(
  title: string,
  message: string,
  ...buttons: ErrorButton[]
) {
  const error: ErrorMessage = {
    title,
    message,
    opened: false,
    buttons,
  };

  const em = get(ErrorMessages);

  em.push(error);

  ErrorMessages.set(em);
}

export function createErrorAppData(data: ErrorMessage): App {
  const error: App = {
    info: {
      name: data.title,
      description: "ArcOS.Desktop.ErrorLogic.Window",
      builtin: true,
      version: ArcOSVersion,
      author: "Generated by ArcOS",
    },
    size: { w: 360, h: 130 },
    pos: { x: 30, y: 40 },
    minSize: { w: 360, h: 130 },
    maxSize: { w: 700, h: 320 },
    controls: { min: false, max: false, cls: true },
    state: {
      headless: false,
      resizable: false,
      windowState: { min: false, max: false, fll: false },
    },
    content: null,
    glass: false,
  };

  error.id = `error#${Math.floor(Math.random() * 1e9)}`;

  return error;
}
