import { get } from "svelte/store";
import icon from "../../assets/apps/errordialog.svg";
import type { App } from "../applogic/interface";
import { maxZIndex } from "../applogic/store";
import { Log } from "../console";
import { ArcOSVersion } from "../env/main";
import {
  ErrorButton,
  ErrorMessage,
  ErrorMessages,
  ErrorWindowStore,
} from "./app";
import { LogLevel } from "../console/interface";

export function getErrorElement(id: string): HTMLDivElement {
  Log(
    "errorlogic/main.ts: getErrorElement",
    `Getting error element of ${id}`,
    LogLevel.info
  );

  const el = document.querySelector(`window#${id}`);

  return el as HTMLDivElement;
}

export function errorMessage(
  title: string,
  message: string,
  image?: string,
  parentId?: string,
  ...buttons: ErrorButton[]
) {
  Log(
    "errorlogic/main.ts: errorMessage",
    `Generating "${title}"`,
    LogLevel.info
  );

  const error: ErrorMessage = {
    title,
    message,
    opened: false,
    buttons,
    id: Math.floor(Math.random() * 1e10),
    image,
    parentId,
  };

  const em = get(ErrorMessages);

  em.push(error);

  ErrorMessages.set(em);

  createErrorAppData(error);
}

export function closeError(id: number) {
  Log("errorlogic/main.ts: closeError", `Closing error ${id}`, LogLevel.info);

  const ews = get(ErrorWindowStore);

  for (let i = 0; i < ews.length; i++) {
    if (ews[i].id == `error_${id}`) {
      ews[i].opened = false;

      setTimeout(() => {
        ews.splice(i, 1);

        ErrorWindowStore.set(ews);
      }, 500);
    }
  }

  ErrorWindowStore.set(ews);
}

export function openError(id: number) {
  Log("errorlogic/main.ts: openError", `Opening error ${id}`, LogLevel.info);

  const ews = get(ErrorWindowStore);

  for (let i = 0; i < ews.length; i++) {
    if (ews[i].id == `error_${id}`) ews[i].opened = true;
  }

  ErrorWindowStore.set(ews);
}

export function createErrorAppData(data: ErrorMessage) {
  Log(
    "errorlogic/main.ts: createErrorAppData",
    `Generating error appData for ${data.title}`,

    LogLevel.info
  );

  const error: App = {
    info: {
      name: data.title,
      description: "ArcOS.Desktop.ErrorLogicwindow",
      builtin: true,
      version: ArcOSVersion,
      author: "Generated by ArcOS",
      icon: data.image || icon,
    },
    size: { w: NaN, h: NaN },
    pos: { x: 60, y: 60 },
    minSize: { w: 200, h: NaN },
    maxSize: { w: 600, h: NaN },
    controls: { min: false, max: false, cls: true },
    state: {
      headless: false,
      resizable: false,
      windowState: { min: false, max: false, fll: false },
    },
    content: null,
    glass: false,
    id: `error_${data.id}`,
    opened: false,
    parentId: data.parentId,
  };

  const ews = get(ErrorWindowStore);

  ews.push(error);

  ErrorWindowStore.set(ews);

  setTimeout(() => {
    openError(data.id);

    const el = document.querySelector(`window#${error.id}`) as HTMLDivElement;

    if (!el)
      return Log(
        "ErrorLogic: createErrorAppData",
        `Can't bring window ${error.id} to front, no associated element could be found.`,
        LogLevel.error
      );

    maxZIndex.set(get(maxZIndex) + 1);

    el.style.zIndex = `${get(maxZIndex)}`;
  }, 5);
}
